version: '3'

services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        working_dir: /var/www/html
        volumes:
            - $PYEmu/Docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - $PYEmu/src:/var/www/html
        
    php:
        build: ./php/
        working_dir: /var/www/html
        volumes:
            - $PYEmu/Docker/php/config/www.conf:/etc/php7/php-fpm.d/www.conf
            - $PYEmu/s